# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'enum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nenum.proto\")\n\x08\x45yeColor\x12\x1d\n\teye_color\x18\x01 \x01(\x0e\x32\n.EYE_COLOR*O\n\tEYE_COLOR\x12\x19\n\x15\x45YE_COLOR_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x45YE_COLOR_BLUE\x10\x01\x12\x13\n\x0f\x45YE_COLOR_GREEN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EYE_COLOR']._serialized_start=57
  _globals['_EYE_COLOR']._serialized_end=136
  _globals['_EYECOLOR']._serialized_start=14
  _globals['_EYECOLOR']._serialized_end=55
# @@protoc_insertion_point(module_scope)
